
using Infrastructure.Extentions;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;


var builder = WebApplication.CreateBuilder(args);

// Database
builder.Services.AddDbContext<ApplicationDbContext>(options =>
{
    options.UseSqlServer(
        builder.Configuration.GetConnectionString("DefaultConnection"),
        sqlOptions =>
        {
            sqlOptions.MigrationsAssembly("Infrastructure");
        });
});

// Identity
builder.Services.AddCustomIdentity();
builder.Services.AddInfrastructure();

// Authentication
builder.Services.AddAuthentication();

// MVC / Controllers
builder.Services.AddControllers();

// Swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApi();

// MediatR
builder.Services.AddMediatR(config =>
{
    config.RegisterServicesFromAssembly(
        typeof(Application.Features.Auth.Commands.Register.RegisterCommand)
            .Assembly);
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi(); // Exposes the raw JSON file
    app.UseSwaggerUI(options =>
    {
        // Tell Swagger UI to read the JSON file generated by .NET 10
        options.SwaggerEndpoint("/openapi/v1.json", "CQRS API v1");
        
        // Sets Swagger as the default home page (e.g., https://localhost:xxxx/)
        options.RoutePrefix = string.Empty; 
    });// Exposes the UI dashboard at /scalar/v1
}

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();